config/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.i18n import set_language

urlpatterns = [
        path('set_language/', set_language, name='set_language'),
]

urlpatterns += i18n_patterns(
        path('admin/', admin.site.urls),
        path('', include('expenses.urls')),
        path('accounts/', include('django.contrib.auth.urls')),
        path('accounts/', include('core.urls')),
        path("__debug__/", include("debug_toolbar.urls")),
)

core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('signup', views.SignupView.as_view(), name='signup'),
]

expenses/urls.py
from django.urls import path
from django.conf.urls.i18n import i18n_patterns

from . import views

app_name = 'expenses'

urlpatterns = (
    path('', views.group_list_view, name='group-list'),
    path('profile/', views.profile_view, name='profile'),
    path('detail/<int:pk>/', views.group_detail_view, name='group-detail'),
    path('detail/<int:pk>/edit/', views.GroupUpdateView.as_view(), name='group-edit'),
    path('detail/<int:pk>/expenses/new/', views.create_expense_view, name='group-expense-new'),
    path('<int:pk>/transaction/', views.create_transactions_view, name='transaction-new'),

)

expenses/models.py
from django.db import models
from django.conf import settings


# Create your models here.

class Group(models.Model):
    name = models.CharField(max_length=150)
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='grupes')

    def __str__(self):
        return self.name


class Expense(models.Model):
    grupe = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='expenses')
    description = models.CharField(max_length=150)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    datetime_created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='expenses')
    participants = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='participants_expenses')

    def __str__(self):
        return f'{self.amount} {self.description}, {self.created_by.first_name}'


class Transaction(models.Model):
    expense = models.ForeignKey(Expense, on_delete=models.CASCADE, related_name='transactions')
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='transactions')
    to_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='gettransactions')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    datetime_created = models.DateTimeField(auto_now_add=True)


class Account(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    balance = models.DecimalField(max_digits=10, decimal_places=2)

expenses/forms.py
from django import forms

from expenses.models import Group, Expense, Transaction


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name', 'members']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'members': forms.CheckboxSelectMultiple(),
        }


class GroupUpdateForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name', 'members']


class AddMemberForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['members']


class ExpensesForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['grupe', 'description', 'created_by', 'amount', 'participants']
        widgets = {
            'grupe': forms.HiddenInput(),
            'created_by': forms.HiddenInput(),
            'participants': forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        group = kwargs.pop('group', None)
        current_user = kwargs.pop('current_user', None)
        super().__init__(*args, **kwargs)
        if group:
            self.fields['participants'].queryset = group.members.exclude(id=current_user.id)


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['from_user', 'to_user', 'amount', 'expense']

        widgets = {
            'from_user': forms.HiddenInput(),
            'to_user': forms.HiddenInput(),
            'amount': forms.HiddenInput(),
            'expense': forms.HiddenInput(),
        }

expenses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views import generic

from . import models
from . import forms


# Create your views here.
@login_required(login_url='login')
def profile_view(request):
    account = get_object_or_404(models.Account, user=request.user)
    return render(request, 'profile_detail.html', {'account': account})


@login_required()
def group_list_view(request):
    if request.method == 'POST':
        form = forms.GroupForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Group Created!')
    form = forms.GroupForm()
    groups = models.Group.objects.filter(members=request.user)
    context = {
        'groups': groups,
        'form': form,
    }
    return render(request, 'group_list_view.html', context)


@login_required()
def group_detail_view(request, pk):
    member_form = forms.AddMemberForm()
    group = get_object_or_404(models.Group.objects.prefetch_related('members'), pk=pk)
    group_members = group.members.all()
    expenses = models.Expense.objects.filter(grupe=group).select_related('grupe')
    if request.user not in group_members:
        messages.error(request, 'You are not allowed to view this group')
        return redirect('expenses:group-list')

    else:
        context = {
            'expenses': expenses,
            'group': group,
            'group_members': group_members,
            'member_form': member_form,
        }
        return render(request, 'group_detail_view.html', context)


class GroupUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = models.Group
    form_class = forms.GroupUpdateForm
    template_name = 'grupe_update.html'

    def get_success_url(self):
        pk = self.kwargs.get('pk')
        return reverse_lazy('expenses:group-detail', kwargs={'pk': pk})


@login_required()
def create_expense_view(request, pk):
    group = get_object_or_404(models.Group, pk=pk)

    if request.method == 'POST':
        form = forms.ExpensesForm(request.POST, group=group, current_user=request.user)
        if form.is_valid():
            expense = form.save(commit=False)
            expense.created_by = request.user
            expense.grupe = group
            expense.save()
            form.save_m2m()
            return redirect('expenses:group-detail', pk=group.id)
    else:
        form = forms.ExpensesForm(group=group, current_user=request.user, initial={
            'created_by': request.user,
            'grupe': group,
        })

    return render(request, 'expense_create_view.html', {'form': form})


@login_required()
def create_transactions_view(request, pk):
    current_user = request.user
    form = forms.TransactionForm()
    expenses = get_object_or_404(models.Expense.objects.select_related('grupe'), id=pk)
    participants = expenses.participants.all()
    share_per_person = round(expenses.amount / participants.count(), 2)
    payment_status = []

    for participant in participants:
        is_paid = models.Transaction.objects.filter(from_user=participant, expense=expenses).exists()
        payment_status.append((participant, is_paid))

    if request.method == 'POST':
        form = forms.TransactionForm(request.POST)
        if form.is_valid():
            transaction = form.save(commit=False)
            from_account = get_object_or_404(models.Account, user=transaction.from_user)
            to_account = get_object_or_404(models.Account, user=expenses.created_by)

            if from_account.balance >= share_per_person:
                from_account.balance -= share_per_person
                to_account.balance += share_per_person
                from_account.save()
                to_account.save()
                transaction.save()
                return redirect('expenses:group-detail', pk=expenses.grupe.id)
            else:
                form.add_error(None, f'Insufficient balance: Your account balance is {from_account.balance}.')
    is_paid = False
    in_participants = False
    is_creator = False
    if request.method == 'GET':
        if models.Transaction.objects.filter(from_user=current_user, expense=expenses).exists():
            is_paid = True
        if current_user not in list(participants):
            in_participants = True
        if request.user == expenses.created_by:
            is_creator = True
        form = forms.TransactionForm(initial={
            'from_user': current_user,
            'to_user': expenses.created_by,
            'amount': share_per_person,
            'expense': expenses,

        })

    return render(request, 'transaction_create.html', {
        'form': form,
        'share_per_person': share_per_person,
        'is_paid': is_paid,
        'is_creator': is_creator,
        'in_participants': in_participants,
        'participants': participants,
        'expenses': expenses,
        'payment_status': payment_status,
    })

expenses/templates/expense_create_view.html
{#{% extends '_Base.html' %}#}
{##}
{#{% block title %}#}
{#	Create Expense Page#}
{#{% endblock title %}#}
{##}
{#{% block content %}#}
{#    <form action="" method="post">#}
{#        {% csrf_token %}#}
{#        {{ form }}#}
{#        <button type="submit">ثبت</button>#}
{#    </form>#}
{#{% endblock content %}#}



{% extends '_Base.html' %}
{% load i18n %}

{% block title %}
    Create Expense Page
{% endblock title %}

{% block content %}
    <div class="container mt-4">
        <h1 class="mb-4">{% translate 'create new expense' %}</h1>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            {{ form }}
                            <button type="submit" class="btn btn-primary">{% translate 'submit' %}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

expenses/templates/group_detail_view.html
{#{% extends '_Base.html' %}#}
{##}
{#{% block title %}#}
{#    Grupe Detail View#}
{#{% endblock %}#}
{##}
{#{% block content %}#}
{#    {% for member in group_members %}#}
{#        <li>{{ member.username }}</li>#}
{#    {% endfor %}#}
{#    <a href="{% url 'expenses:group-edit' group.id %}">#}
{#        <button type="submit"> edit group</button>#}
{#    </a>#}
{#    <br>#}
{#    <hr>#}
{#    {% for expense in expenses %}#}
{#        <div>#}
{#            {{ expense.created_by }}#}
{#            {{ expense.description }}#}
{#            {{ expense.amount }}#}
{#            {{ expense.datetime_created }}#}
{#            {% if request.user != expense.created_by  %}#}
{#                <a href="{% url 'expenses:transaction-new' pk=expense.id %}">#}
{#                    <button>جزیات</button>#}
{#                </a>#}
{#            {% else %}#}
{#                <button disabled>جزیات</button>#}
{#            {% endif %}#}
{#        </div>#}
{#        ------------------------------#}
{#    {% endfor %}#}
{#    <hr>#}
{#    <div>#}
{#        <a href="{% url 'expenses:group-expense-new' group.id %}">#}
{#            <button>ایجاد یک هزینه</button>#}
{#        </a>#}
{#    </div>#}
{#    <br><br>#}
{#    <div>#}
{#        <a href="{% url 'expenses:group-list' %}">#}
{#            <button>back to list view</button>#}
{#        </a>#}
{#    </div>#}
{##}
{##}
{#{% endblock content %}#}

{% extends '_Base.html' %}
{% load i18n %}

{% block title %}
    Grupe Detail View
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <h1 class="mb-4">{% translate 'Group Detail' %}</h1>

        <div class="mb-4">
            <h2 class="mb-3"> {% translate 'members' %}</h2>
            <ul class="list-group">
                {% for member in group_members %}
                    <li class="list-group-item">{{ member.username }}</li>
                {% endfor %}
            </ul>
        </div>
        <a href="{% url 'expenses:group-edit' group.id %}">
            <button type="submit"> {% translate 'edit group' %}</button>
        </a>
        <hr class="my-4">

        <div class="mb-4">
            <h2 class="mb-3">{% translate 'expenses' %}</h2>
            {% for expense in expenses %}
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{% translate 'created by' %} {{ expense.created_by }}</h5>
                        <p class="card-text">
                            <strong>{% translate 'description' %}:</strong> {{ expense.description }}<br>
                            <strong>{% translate 'amount' %}:</strong> {{ expense.amount }}<br>
                            <strong>{% translate 'date' %}:</strong> {{ expense.datetime_created }}
                        </p>
{#                        {% if request.user != expense.created_by %}#}
                            <a href="{% url 'expenses:transaction-new' pk=expense.id %}" class="btn btn-primary">
                                {% translate 'detail' %}
                            </a>
{#                        {% else %}#}
{#                            <button class="btn btn-secondary" disabled>جزیات</button>#}
{#                        {% endif %}#}
                    </div>
                </div>
            {% endfor %}
        </div>

        <hr class="my-4">

        <div class="mb-4">
            <a href="{% url 'expenses:group-expense-new' group.id %}" class="btn btn-success">
                  {% translate 'create new expense' %}
            </a>
        </div>
        <div>
            <a href="{% url 'expenses:group-list' %}" class="btn btn-secondary">
                 {% translate 'back to list of group' %}
            </a>
        </div>
    </div>
{% endblock %}

expenses/templates/group_list_view.html
{#{% extends '_Base.html' %}#}
{##}
{#{% block title %}#}
{#    <h1>Grupe List Page</h1>#}
{#{% endblock title %}#}
{##}
{#{% block content %}#}
{#    <form action="" method="POST">#}
{#        {% csrf_token %}#}
{#        {{ form }}#}
{#        <button type="submit"> ثبت</button>#}
{#    </form>#}
{#    {% for group in groups %}#}
{#        <a href="{% url 'expenses:group-detail' group.id %}">#}
{#            <li>{{ group.name }}</li>#}
{#        </a>#}
{#    {% endfor %}#}
{##}
{#{% endblock content %}#}

{% extends '_Base.html' %}
{% load i18n %}

{% block title %}
    <h1 class="text-center my-4">{% translate 'Grupe List Page' %}</h1>
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row mb-4">
            <div class="col-md-6 offset-md-3">
                <h2 class="mb-3">{% translate 'create new group' %}</h2>
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        {{ form.name }}
                    </div>
                    <div class="mb-3">
                        {{ form.members }}
                    </div>
                    <button type="submit" class="btn btn-primary">{% translate 'submit' %}</button>
                </form>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h2 class="mb-3">{% translate 'list of groups' %}</h2>
                <ul class="list-group">
                    {% for group in groups %}
                        <li class="list-group-item">
                            <a href="{% url 'expenses:group-detail' group.id %}" class="text-decoration-none">
                                {{ group.name }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}

expenses/templates/grupe_update.html
{% extends '_Base.html' %}

{% block title %}

{% endblock title %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit"> edit </button>
    </form>
{% endblock content %}

expenses/templates/profile_detail.html
{% extends '_Base.html' %}

{% block title %}

{% endblock title %}

{% block content %}
    <div>
        {{ account.user.username }}
    </div>
    <div>
        <p>
            your account balance is : {{ account.balance }}
        </p>
    </div>
{% endblock content %}

expenses/templates/transaction_create.html
{#{% extends '_Base.html' %}#}
{##}
{#{% block title %}#}
{#    Create Transaction Page#}
{#{% endblock title %}#}
{##}
{#{% block content %}#}
{#    {% for participant in participants %}#}
{#    	<li>{{ participant.username }}</li>#}
{#    {% endfor %}#}
{##}
{#    <p>your share is {{ share_per_person }}</p>#}
{#    {% if is_paid %}#}
{#        شما نیازی به پرداخت کردن ندارید#}
{#    {% elif in_participants %}#}
{#        <p>شما در این هزینه سهم ندارید </p>#}
{#    {% else %}#}
{#        <form action="" method="POST">#}
{#            {% csrf_token %}#}
{#            {{ form }}#}
{#            <button type="submit">پرداخت</button>#}
{#        </form>#}
{##}
{#    {% endif %}#}
{#{% endblock content %}#}


{% extends '_Base.html' %}

{% block title %}
    Create Transaction Page
{% endblock title %}

{% block content %}
    <div class="container mt-4">
        <h1 class="mb-4">ایجاد تراکنش</h1>

        <!-- نمایش شرکت‌کنندگان -->
        <div class="mb-4">
            <h2 class="mb-3">شرکت‌کنندگان</h2>
            <ul class="list-group mb-3">
                {% for participant in participants %}
                    <li class="list-group-item">{{ participant.username }}</li>
                {% endfor %}
            </ul>
        </div>

        {% if is_creator %}
            <h2 class="mb-3">وضعیت پرداخت ها</h2>
            <ul class="list-group mb-3">
                {% for participent, is_paid in payment_status %}
                    <li class="list-group mb-3">
                        {{ participent.username }}
                        {% if is_paid %}
                            پرداخت شده است ✅
                        {% else %}
                            پرداخت ندشه است ❌
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        <!-- بررسی وضعیت پرداخت -->
        {% if is_paid %}
            <div class="alert alert-success" role="alert">
                شما نیازی به پرداخت کردن ندارید.
            </div>
        {% elif in_participants %}
            <div class="alert alert-warning" role="alert">
                شما در این هزینه سهم ندارید.
            </div>
        {% else %}
            <div class="card">
                <div class="card-body">
                    <h3 class="mb-4">پرداخت</h3>
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ form }}
                        <button type="submit" class="btn btn-primary">پرداخت</button>
                    </form>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock content %}